### PR TITLE
Proper attribution for hsivonen's blog post

### LINKED ISSUE #16: Get an OK from Henri Sivonen to quote their emails, blog posts, etc.
https://htmlparser.info/preface/#acknowledgements

> Thanks to [...] Henri Sivonen, [...] for letting me quote their emails, blog posts, etc\. in this book\. TODO

@hsivonen is this OK? (There are no new quotes since you reviewed.)

### PR DESCRIPTION
**Pull request by zcorpan**
Fixes #16.

---

@hsivonen

### CODE REVIEW

**Comment by hsivonen** [comment]
Looking at the checklist at https://wiki.creativecommons.org/wiki/License_Versions#Detailed_attribution_comparison_chart , it seems that the copyright notice is  missing.

Maybe it makes more sense to put the copyright notice and the license name and link into a footnote or similar on the page https://htmlparser.info/parser/ which already has the name of the author and the link to the original?

**Comment by zcorpan** [comment]
Apologies, fixed. I moved the notice and license to the parser chapter.

**Comment by zcorpan** [comment]
@hsivonen I've stated how it's modified as well. The rendered preview can be viewed at https://deploy-preview-20--htmlparser-info.netlify.com/parser/#the-last-of-the-parsing-quirks

**Comment by zcorpan** [comment]
@hsivonen ping

**Comment by hsivonen** [comment]
Sorry, I misread earlier notification and though this had landed. It seems to me it meets the checklist.

**Pull request merged**
